[versions]
kotlin = "2.1.0"
compose = "1.7.0"
platform= "2.2.1"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "platform" }
