[versions]
kotlin = "2.1.20"
compose = "1.8.0"
intellij = "2.5.0"


[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }
